In [26]:
# While loop
starfoxteam = ["Fox", "Slippy", "Peppy", "Falco"]

i = 1
while i <= length(starfoxteam)
    member = starfoxteam[i]
    println("Member $i: $member")
    i +=1
end

# For loop
pokemonteam = ["Pikachu", "Jolteon", "Jigglypuff", "Venusaur", "Mew", "Zapdos"]

for pokemon in pokemonteam
    println("I choose you, $pokemon !")
end


Member 1: Fox
Member 2: Slippy
Member 3: Peppy
Member 4: Falco
I choose you, Pikachu !
I choose you, Jolteon !
I choose you, Jigglypuff !
I choose you, Venusaur !
I choose you, Mew !
I choose you, Zapdos !


In [25]:
# Matrix operations
m,n = 5,10
X = zeros(m,n)

for x in 1:m
    for y in 1:n
        X[x,y] = x + y
    end
end

Y = zeros(m,n)
for i in 1:m, j in 1:n
    Y[i,j] = i + j
end

for n in 1 : 10
    A = [i + j for i in 1:n, j in 1:n]
    display(A)
end

1×1 Array{Int64,2}:
 2

2×2 Array{Int64,2}:
 2  3
 3  4

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Array{Int64,2}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Array{Int64,2}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Array{Int64,2}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20

In [31]:
# Functions
function saymyname(nm)
    println("You're actin' kinda crazy, $nm, ain't callin' me baby\n")
end
saymyname("Destiny's Child")

function f(x)
    x^2
end
f(2)

You're actin' kinda crazy, Destiny's Child, ain't callin' me baby



4

In [33]:
hellowhroled(nm) = println("Hellow, $nm")
y(x) = x^2

hellowhroled("Bob Ross")
y(20)

Hellow, Bob Ross


400

In [37]:
getPot = dealer -> println("Hello, $dealer, I'd like some of your best pot")
calc2 = x -> x^2
getPot("Henry")
calc2(10)

2×3 Array{Float64,2}:
 0.543335  0.843282   0.186469
 0.4383    0.0156849  0.257061

Hello, Henry, I'd like some of your best pot


100

In [78]:
m = x -> rand(1:length(x))
M = rand(2,3)
N = m(M)
display(N)

2

In [ ]:
# Duck-typing
